### ISSUE TITLE
it takes a long time for video play

### ISSUE THREAD

**Issue by mrbontor** [kevinGodell/ffmpeg-streamer#1]
i trying to use version 0.0.7 with ffmpeg v. 3.4 in windows.
while i run this app with type RTSP, it takes a long time for the video to play
have i miss something or what i should to do in settings before i run this app?

**Comment by kevinGodell** [comment]
@mrbontor Thanks for the inquiry. I need a little more info, if you don't mind. 

What version of windows are you running the app on, windows 7 64 or 8 or 10?

 Is the app running as the clickable binary, or are you running it from a cloned directory using npm start? 

What browser and operating system are you trying to watch the video(each browser on different OS handles the videos differently)? 

Which video type is taking long to play, there are 6 different types on the page? If they are all taking long, then it may be that the video input could be the problem.

Please use the latest release [v0.0.10](https://github.com/kevinGodell/ffmpeg-streamer/releases/tag/v0.0.10), much has changed internally to improve video streaming(I hope). If you can run it again, can you post the ffmpeg params, codec info,  and m3u8 playlist from the video player page? Thanks for trying!

**Comment by mrbontor** [comment]
i used windows 10 64x with ffmpeg 64x and  i've tried both on firefox and chrome that are updated.
* i prefer to use cloned directory.



there's a funny thing, when i run this for the first time (I mean when my laptop was just turned on), video is quite smothe except for mp4 type. and after that, its happen for 6 videos type even jpeg.

[this](https://github.com/kevinGodell/ffmpeg-streamer/files/1822204/123.txt) is my last log on my practicing. but i will try to use last version. thanks

**Comment by kevinGodell** [comment]
From your logs, I can see that you were using a local rtsp cam and that your were encoding video with libx264.  From my personal use, I always found codec copy to stream the best since ffmpeg won’t be using so much cpu to transcode.  Be warned, when using libx264, you will have to tweak settings to make it play good. You might have to set the profile, level, etc. Keep in mind that some ip cams cannot handle multiple connections. So if you have some other software already consuming the video, that could affect things.

On my latest version I changed the movflags and found it to work a bit better in the browser. About the progressive mp4, I would never expect it to play good. I only put that there for comparison.

**Comment by mrbontor** [comment]
thank you @kevinGodell.
im very thanks for your suggestions and that's true, my laptop crashed, :D 

i've tried to use the lastest version, there's an error with hls video type.
GET /hls/test.m3u8 503 1.034 ms - 14
GET /hls/test.m3u8 503 0.490 ms - 14
GET /hls/test.m3u8 503 0.707 ms - 14
GET /hls/test.m3u8 503 0.960 ms - 14
GET /hls/test.m3u8 503 0.507 ms - 14
GET /hls/test.m3u8 503 0.472 ms - 14
GET /hls/test.m3u8 503 0.585 ms - 14
GET /hls/test.m3u8 503 0.580 ms - 14

**Comment by kevinGodell** [comment]
Those logs are normal because hls.js and other files ares requesting the m3u8 before it is ready. It will only be ready after ffmpeg spits out the first segment, which may be few seconds. For example, if the segment duration is 6 seconds output from you cam based on its internal settings, then you would have to wait 6 seconds for any of the mp4 encoded video to start playing. 

I put out that 503 error code on purpose to test hls.js and its attempts to keep requesting the files before finally giving up.

Remember, this software was made for testing purposes.

**Comment by mrbontor** [comment]
thanks for your support @kevinGodell 
now i got it and how this app works,

btw, sorry for my bad language. thanks.

**Comment by kevinGodell** [comment]
No apologies needed, your language is fine. If you have any more questions, keep it coming. I will keep this open for a few days.

**Comment by mrbontor** [comment]
thanks dude.

**Comment by kevinGodell** [comment]
Its been 4 days, so I will close this now. If you have any more problems, open a new issue. Good luck.
