### ISSUE TITLE
Chunked-encoding streaming output

### ISSUE THREAD

**Issue by felipewd** [kevinGodell/ffmpeg-streamer#5]
Hi @kevinGodell,

Great project! I've been playing with it for the last few days and enjoying it very much :-)

I've been trying to use your project to create a CMAF-compatible fMP4 output.

For this to work the server would have to stream the last-not-yet-finished response using chunked-encoding (since there's no correct content-length yet). Is it possible?

On the ffmpeg-side, it's possible to instruct it to output such streams using the dash muxer with the `streaming=1` , `hls_playlist`...and just for fun (since you're using hls.js as the HLS player)...the `lhls` option could be used to instruct the player to enable the low latency options.

Would this be possible?

**Comment by kevinGodell** [comment]
Hello @felipewd,
Thanks for the comment. This sounds interesting, but I must admit that I have not experimented with ffmpeg for quite some time. What information would be in the last-not-yet-finished response? Is that an unfinished media segment?

- [ ] Can you give me some sample ffmpeg full commands that do what you are suggesting? 

- [ ] Can you also give me some links to any documentation that might educate me on the subject?

**Comment by felipewd** [comment]
Hi @kevinGodell,

Sure thing, the gist of the theory is this:

- For HLS, let's say we defined a 4s chunk for the fMP4/ts;
- The normal way is for ffmpeg to generate the 4s-chunk, save it to disk and then add it to the m3u8, right? This than can be delivered using a content-length by the web server, because the segment is complete;
- For CMAF, the m3u8 is updated as soon as the first few bytes of the segment are being written; So for the player to able to play it correctly, the webserver has to send it using chunked-encoding, because the file is not complete yet; `ffmpeg` supports this using the options I told you. But for this to work, a few options have to be respected (such as the ones you're using on your `mp4frag` component), such as begin each segment with a keyframe + empty moov, etc.

There's a demo here: http://mediapm.edgesuite.net/will/dash/lowlatency/low-latency-public-example.html

And the code for ffmpeg is available also: https://github.com/jkarthic-akamai/ABR-Broadcaster.

But your example is way simpler (and nicer!) so I'd like to adapt the missing components to make this work :-)

**Comment by kevinGodell** [comment]
I see now. That is a new feature added to the latest ffmpeg. I found a little talk about it @ https://stackoverflow.com/questions/56700705/how-to-enable-lhls-in-ffmpeg-4-1

Currently, I have noticed that ffmpeg will buffer the segments and only output one when it is complete, thus always causing an extra delay. I had tried so many options to make ffmpeg start to output the segment before it was complete, but found no way. I guess that new `lhls` option would allow this to work. If you can point me to a pre-compiled windows or mac version of ffmpeg that already has this feature available, I could play with it and take a look at the output.

**Comment by felipewd** [comment]
Hey @kevinGodell,

I know of static binaries only for linux :-(

https://johnvansickle.com/ffmpeg/

Not sure that are pre-compiled git-versions of ffmpeg. 

Do those help? :-)

**Comment by felipewd** [comment]
Oh, it turns out there is one for mac:

https://evermeet.cx/ffmpeg/

I tested this one:

https://evermeet.cx/ffmpeg/ffmpeg-94264-g74d4fd0822.dmg

And it worked with the latest options. :-)

**Comment by kevinGodell** [comment]
Unfortunately, I was not able to get dash to output the EXT-X-PREFETCH data using the new lhls flag. Ffmpeg did read the flag, but I saw no output change. 

Mp4frag (in my project) will not be able to simulate this feature since it just uses mp4 output from ffmpeg to accomplish this. Ffmpeg does not output a segment until it is complete due to the nature of mp4's structure.

If you are intending to reduce video delay, then currently your best option is to set the video source to have smaller chunks by setting its iframe interval to its lowest setting. For example, one of my ip cams can go down to an iframe interval of 1, which gives me about a 1.5 second delay from parsing the chunk and delivering it to client side.

All of that is just a guess because I don't know if you are re-streaming live video, encoding the video, or copying and then re-muxing it.

**Comment by wangmaoguo** [comment]
Hello , this is a great project , and now i am trying to use it .but now i have a different issue.
How can I use this program to process multiple requests?

for example:
Now I have more than one rtsp request, how can i handle these requests?

**Comment by felipewd** [comment]
hey @kevinGodell,

Apparently the LHLS magic only happens when a HTTP output is selected. If you're trying to use a file-output it won't work.

**Comment by kevinGodell** [comment]
Yeah, I wonder why they have that limitation. I guess maybe because it is still experimental. If they really can push out a part of a dash's mp4 segment before it is complete, then maybe they can do that for regular mp4 files. I always read that the segment must be complete so that ffmpeg can make a 2nd pass to move some data around, but maybe that is not true. Perhaps we should make an enhancement request to ffmpeg to start pushing out mp4 partial segments?

**Comment by felipewd** [comment]
hey @kevinGodell, I looked at the code and it doesn't seem too difficult to adapt it to make this work in file-output.

So we could make a patch and send to the ffmpeg-guru review and give us feedback, what do you think?

Cheers :-)

**Comment by kevinGodell** [comment]
Hi @felipewd. I just stumbled across some ffmpeg params last night that help me to reduce latency when re-streaming my ip cams to my browser without needing to re-encode the video to shorten the segment duration. A combination of -movflags frag_every_frame && -min_frag_duration 500000 helps me to produce 0.5 second duration segments that can be delivered much sooner than waiting for the natural end of the segment at the iframe interval.
